# Generated by Django 3.1.1 on 2021-02-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_resources', '0003_auto_20210222_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('image_url', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('stock', models.BooleanField(default=True)),
            ],
        ),
    ]
