# Generated by Django 3.1.1 on 2021-02-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_resources', '0004_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='productos',
            name='section',
            field=models.CharField(max_length=30),
        ),
    ]
