# Generated by Django 3.1.1 on 2021-02-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_resources', '0005_auto_20210223_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iduser', models.IntegerField()),
                ('idproduct', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('date', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
