# Generated by Django 3.1.1 on 2021-02-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_resources', '0006_carrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iduser', models.IntegerField()),
                ('totalprice', models.FloatField()),
                ('date', models.CharField(max_length=30)),
                ('hour', models.CharField(max_length=20)),
            ],
        ),
    ]
